config/routes.rb
Rails.application.routes.draw do
  get "/top" => "items#top"

  get "/about" => "items#about"

  get 'favorites/create'

  get 'favorites/destroy'

  get 'takes/create'

  get 'takes/destroy'

  get 'users/index'

  get 'users/show'


  devise_for :users, :controllers => {
   :registrations => 'users/registrations' 
  }

  resources :users do
  	get :takes, on: :member
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    get :favorites, on: :member
  end
  resources :lessons do
  	resource :takes, only: [:create, :destroy]
    get :takers, on: :member
    resource :reviews, only: [:create, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
  end
  root 'lessons#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lessons, dependent: :destroy
  has_many :takes, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship', foreign_key: :following_id
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :followed_id
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :following

  mount_uploader :image, ImageUploader

  validates :name,
    presence: true,
    length: { maximum: 8 }
  validates :username,
  	presence: true,
  	uniqueness: true,
  	length: { maximum: 15 },
  	format: { with: /\A[a-z0-9]+\z/i }
  validates :bio, length: { maximum: 160 } 

  def followed_by? user
    passive_relationships.find_by(following_id: user.id).present?
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).per(20).order(created_at: :desc)
  end

  def show
  	@user = User.find(params[:id])
    @user_reviews = @user.reviews.order(created_at: :desc)
    @takes = @user.takes.order(created_at: :desc)
  end

  def takes
  	@user = User.find(params[:id])
    @user_lessons = @user.lessons.order(created_at: :desc)
  end

  def follows
  	@user = User.find(params[:id])
  	@follows = @user.followings.page(params[:page]).per(20).order(created_at: :desc)
  end

  def followers
  	@user = User.find(params[:id])
  	@followers = @user.followers.page(params[:page]).per(20).order(created_at: :desc)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/followers.html.erb
<div class="box">
<div class="page-header">
  <h1>フォロワー一覧 <i class="fa fa-users" aria-hidden="true"></i></h1>
</div>

<div class="wrap clearfix">
  <% if @followers.empty? %>
    <div>フォローしていません</div>
  <% else %>
    <% @followers.each do |user| %>
      <div class="users">

        <div class="user-image">
          <% if user.image.present? %>
            <%= link_to user_path(user) do %>
              <%= image_tag user.image.url %>
            <% end %>
          <% else %>
            <%= link_to user_path(user) do %>
              <%= image_tag "http://res.cloudinary.com/dj4jxxpze/image/upload/v1507382061/no_image_qzetmh.png" %>
            <% end %>
          <% end %>
        </div>

          <br>
          <%= link_to user_path(user) do %>
            <h4><strong><%= user.name %>@<%= user.username %></strong></h4>
          <% end %>

        <div>
          <% if current_user != user %>
            <% if user.followed_by?(current_user) %>
              <%= link_to user_relationships_path(user), method: :delete do %>
                <button class="btn btn-primary btn-index">フォロー中</button>
              <% end %>
            <% else %>
              <%= link_to user_relationships_path(user), method: :post do %>
                <button class="btn btn-warning btn-index">フォローする</button>
              <% end %>
            <% end %>
          <% else %>
            <%= link_to edit_user_registration_path(current_user) do %>
              <button class="btn btn-success btn-index">
                プロフィール編集 <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
              </button>
            <% end %>
          <% end %>
        </div>

      </div>
    <% end %>
  <% end %>
</div>

<%= paginate @followers %>

<br>
<%= link_to "プロフィールへ", user_path(@user) %>
</div>

app/views/users/follows.html.erb
<div class="box">
<div class="page-header">
  <h1>フォロー一覧 <i class="fa fa-users" aria-hidden="true"></i></h1>
</div>

<div class="wrap clearfix">
  <% if @follows.empty? %>
    <div>フォローしていません</div>
  <% else %>
    <% @follows.each do |user| %>
      <div class="users">

        <div class="user-image">
          <% if user.image.present? %>
            <%= link_to user_path(user) do %>
              <%= image_tag user.image.url %>
            <% end %>
          <% else %>
            <%= link_to user_path(user) do %>
              <%= image_tag "http://res.cloudinary.com/dj4jxxpze/image/upload/v1507382061/no_image_qzetmh.png" %>
            <% end %>
          <% end %>
        </div>

          <br>
          <%= link_to user_path(user) do %>
            <h4><strong><%= user.name %>@<%= user.username %></strong></h4>
          <% end %>

        <div>
          <% if current_user != user %>
            <% if user.followed_by?(current_user) %>
              <%= link_to user_relationships_path(user), method: :delete do %>
                <button class="btn btn-primary btn-index">フォロー中</button>
              <% end %>
            <% else %>
              <%= link_to user_relationships_path(user), method: :post do %>
                <button class="btn btn-warning btn-index">フォローする</button>
              <% end %>
            <% end %>
          <% else %>
            <%= link_to edit_user_registration_path(current_user) do %>
              <button class="btn btn-success btn-index">
                プロフィール編集 <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
              </button>
            <% end %>
          <% end %>
        </div>

      </div>
    <% end %>
  <% end %>
</div>

<%= paginate @follows %>

<br>
<%= link_to "プロフィールへ", user_path(@user) %>
</div>

app/views/users/index.html.erb
<div class="box">
<p><%= notice %></p>
<div class="page-header">
  <h1>学生一覧 <i class="fa fa-users" aria-hidden="true"></i>
</h1>
</div>

<div class="wrap clearfix">
  <% @users.each do |user| %>
    <div class="users">

      <div class="user-image">
        <% if user.image.present? %>
          <%= link_to user_path(user) do %>
            <%= image_tag user.image.url %>
          <% end %>
        <% else %>
          <%= link_to user_path(user) do %>
            <%= image_tag "http://res.cloudinary.com/dj4jxxpze/image/upload/v1507382061/no_image_qzetmh.png" %>
          <% end %>
        <% end %>
      </div>

        <br>
        <%= link_to user_path(user) do %>
          <h4 class="user-h4"><strong><%= user.name %></strong></h4>
          <h4 class="user-h4"><strong>@<%= user.username %></strong></h4>
        <% end %>

      <div>
        <% if current_user != user %>
          <% if user.followed_by?(current_user) %>
            <%= link_to user_relationships_path(user), method: :delete do %>
              <button class="btn btn-primary btn-index">フォロー中</button>
            <% end %>
          <% else %>
            <%= link_to user_relationships_path(user), method: :post do %>
              <button class="btn btn-warning btn-index">フォローする</button>
            <% end %>
          <% end %>
        <% else %>
          <%= link_to edit_user_registration_path(current_user) do %>
            <button class="btn btn-success btn-index">
              プロフィール編集 <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
            </button>
          <% end %>
        <% end %>
      </div>

    </div>
  <% end %>
</div>

<%= paginate @users %>

</div>

app/views/users/show.html.erb
<div class="box">
<div class="prof-wrap">

<!-- プロフィールここから -->
<div class="prof">
<div class="page-header">
  <h1>
    プロフィール <i class="fa fa-user" aria-hidden="true"></i>
  </h1>	
</div>

<% if @user.image.present? %>
  <%= image_tag @user.image.url %>
<% else %>
  <%= image_tag "http://res.cloudinary.com/dj4jxxpze/image/upload/v1507382061/no_image_qzetmh.png" %>
<% end %>

<h3>
  <strong>
    <%= @user.name %><br>
    @<%= @user.username %>
  </strong>
</h3>

<div class="bio">
  <%= @user.bio %>
</div><br>

<% if @user.id == current_user.id %>
  <%= link_to edit_user_registration_path(current_user) do %>
    <button class="btn btn-success btn-prof">
      プロフィール編集 <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
    </button>
  <% end %>
<% else %>
  <% if @user.followed_by?(current_user) %>
  	<%= link_to user_relationships_path(@user), method: :delete do %>
      <button class="btn btn-primary btn-prof">フォロー中</button>
    <% end %>
  <% else %>
    <%= link_to user_relationships_path(@user), method: :post do %>
      <button class="btn btn-warning btn-prof">フォローする</button>
    <% end %>
  <% end %>
<% end %>
<br>
<%= link_to takes_user_path(@user) do %>
  <button class="btn btn-default btn-prof">
    追加した授業 <span class="badge"><%= @user.lessons.count %></span>
  </button>
<% end %>
<br>
<%= link_to follows_user_path(@user) do %>
  <button class="btn btn-default btn-prof">
    フォロー <span class="badge"><%= @user.followings.count %></span>
  </button>
<% end %>
<br>
<%= link_to followers_user_path(@user) do %>
  <button class="btn btn-default btn-prof">
    フォロワー <span class="badge"><%= @user.followers.count %></span>
  </button>
<% end %>
<br>
</div>
<!-- プロフィールここまで -->

<!-- 履修授業一覧ここから -->
<div class="prof-takes">
<div class="page-header">
  <h1>履修授業一覧【<%= @user.takes.count %>】</h1>
</div>
<% if @user.takes.empty? %>
  <span>履修中の授業がありません</span>
<% else %>
  <table class="table table-hover">
    <thead>
    <tr>
        <th>授業名</th>
        <th>教員</th>
        <th class="text-center">レビュー数</th>
        <th class="text-center">履修者数</th>
      </tr>
    </thead>
    <tbody>
        <% @takes.map {|f| f.lesson }.each do |lesson| %>
          <tr>
            <td><%= link_to lesson.title, lesson_path(lesson) %></td>
            <td><%= lesson.teacher %></td>

          <td class="text-center">
            <%= link_to lesson_path(lesson) do %>
              <span class="glyphicon glyphicon-comment" aria-hidden="true"></span> 
              <%= lesson.reviews.count %>
            <% end %>
          </td>

          <td class="text-center">
            <%= link_to takers_lesson_path(lesson) do %>
              <i class="fa fa-user" aria-hidden="true"></i> 
              <%= lesson.takes.count %>
            <% end %>
          </td>

            <td>
              <% if lesson.taken_by? current_user %>
                <%= link_to lesson_takes_path(lesson), method: :delete do %>
                  <button class="btn btn-primary">履修中</button>
                <% end %>
              <% else %>
                <%= link_to lesson_takes_path(lesson), method: :post do %>
                  <button class="btn btn-warning">履修する</button>
                <% end %>
              <% end %>
            </td>
            <td>
              <%= link_to edit_lesson_path(lesson) do %>
                <button class="btn btn-default">編集</button>
              <% end %>
              <% if current_user.id == lesson.user_id %>
                <%= link_to lesson, method: :delete, data: { confirm: "本当によろしいですか？" } do %>
                  <button class="btn btn-default">削除</button>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
    </tbody>
  </table>
<% end %>
</div>
<!-- 履修授業一覧ここまで -->

</div>

<br><br>

<!-- 投稿したレビューここから -->
<div class="prof-reviews">

<div class="page-header">
  <h2>投稿したレビュー <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>【<%= @user.reviews.count %>】</h2>
</div>
<% if @user_reviews.empty? %>
  <div>レビューがありません</div>
<% else %>
  <table class="table table-hover">
    <thead>
    <tr>
        <th>授業名</th>
        <th>教員</th>
        <th>本文</th>
        <th>投稿日時</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @user_reviews.each do |review| %>
        <tr>
          <td class="review-title"><%= link_to review.lesson.title, lesson_path(review.lesson) %></td>
          <td class="review-teacher"><%= review.lesson.teacher %></td>
          <td class="review-body"><%= review.body %></td>
          <td class="review-created_at"><%= review.created_at.strftime('%Y/%m/%d %H:%M') %></td>
          <td class="review-delete">
            <% if current_user.id == review.user_id %>
              <%= link_to lesson_reviews_path(review.lesson), method: :delete, data: { confirm: "本当によろしいですか？"} do %>
                <button class="btn btn-default">削除</button>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

</div>
<!-- 投稿したレビューここまで -->

</div>

app/views/users/takes.html.erb
<div class="box">
<!-- 追加した授業ここから -->
<div class="page-header">
  <h2>追加した授業 <span class="glyphicon glyphicon-book" aria-hidden="true"></span></h2>
</div>
<% if @user.lessons.empty? %>
  <div>追加した授業がありません</div>
<% else %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>授業名</th>
        <th>教員</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @user_lessons.each do |lesson| %>
        <tr>
          <td><%= link_to lesson.title, lesson_path(lesson) %></td>
          <td><%= lesson.teacher %></td>
          <td>
            <% if lesson.taken_by? current_user %>
              <%= link_to lesson_takes_path(lesson), method: :delete do %>
                <button class="btn btn-primary btn-take">履修中</button>
              <% end %>
            <% else %>
              <%= link_to lesson_takes_path(lesson), method: :post do %>
                <button class="btn btn-warning btn-take">履修する</button>
              <% end %>
            <% end %>
          </td>
          <td>
            <%= link_to edit_lesson_path(lesson) do %>
              <button class="btn btn-default">編集</button>
            <% end %>
            <% if current_user.id == lesson.user_id %>
              <%= link_to lesson, method: :delete, data: { confirm: "本当によろしいですか？" } do %>
                <button class="btn btn-default">削除</button>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %><br>
<%= link_to new_lesson_path do %>
  <button class="btn btn-default"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> 新しい授業を追加する</button>
<% end %>
<!-- 追加した授業ここまで -->

<br><br>
<%= link_to "プロフィールへ", user_path(@user) %>
</div>