config/routes.rb
Rails.application.routes.draw do
  get "/top" => "items#top"

  get "/about" => "items#about"

  get 'favorites/create'

  get 'favorites/destroy'

  get 'takes/create'

  get 'takes/destroy'

  get 'users/index'

  get 'users/show'


  devise_for :users, :controllers => {
   :registrations => 'users/registrations' 
  }

  resources :users do
  	get :takes, on: :member
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    get :favorites, on: :member
  end
  resources :lessons do
  	resource :takes, only: [:create, :destroy]
    get :takers, on: :member
    resource :reviews, only: [:create, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
  end
  root 'lessons#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  has_many :takes, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :title, presence: true
  validates :teacher, presence: true
  validates :user_id, presence: true

  def taken_by? user
  	takes.where(user_id: user.id).exists?
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy, :takers]
  before_action :authenticate_user!
  # before_action :correct_user, only: [:edit, :update]
  before_action :correct_user, only: [:destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.page(params[:page]).per(10).order(created_at: :desc)
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @reviews = @lesson.reviews.order(created_at: :desc)
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)
    @lesson.user_id = current_user.id
    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: '授業を追加しました' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: '授業を編集しました' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: '授業を削除しました' }
      format.json { head :no_content }
    end
  end

  def takers
    @lesson = Lesson.find(params[:id])
    @takers = @lesson.takes.order(created_at: :desc)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:title, :teacher, :user_id)
    end
    def correct_user
      lesson = Lesson.find(params[:id])
      if current_user.id != lesson.user.id
        redirect_to root_path
      end
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_with(model: lesson, local: true) do |form| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "授業名" %><br>
    <%= form.text_field :title, id: :lesson_title %>
  </div>

  <div class="field">
    <%= form.label "教員名" %><br>
    <%= form.text_field :teacher, id: :lesson_teacher %>
  </div>

  <div class="actions">
    <%= form.submit "送信" %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<div class="box">
<div class="page-header">
  <h1>授業編集</h1>
</div>

<%= render 'form', lesson: @lesson %>

<%= link_to "授業詳細", @lesson %><br>

<%= link_to "授業一覧", lessons_path %>
</div>

app/views/lessons/index.html.erb
<div class="box">
<div class="page-header">
  <h1>授業一覧 <span class="glyphicon glyphicon-book" aria-hidden="true"></span></h1>
</div>

<% if @lessons.empty? %>
  <div>授業がありません</div>
<% else %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>授業名</th>
        <th>教員</th>
        <th class="text-center">レビュー数</th>
        <th class="text-center">履修者数</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @lessons.each do |lesson| %>
        <tr>

          <td><%= link_to lesson.title, lesson_path(lesson) %></td>
          <td><%= lesson.teacher %></td>

          <td class="text-center">
            <%= link_to lesson_path(lesson) do %>
              <span class="glyphicon glyphicon-comment" aria-hidden="true"></span> 
              <%= lesson.reviews.count %>
            <% end %>
          </td>

          <td class="text-center">
            <%= link_to takers_lesson_path(lesson) do %>
              <i class="fa fa-user" aria-hidden="true"></i> 
              <%= lesson.takes.count %>
            <% end %>
          </td>

          <td>
            <% if lesson.taken_by? current_user %>
              <%= link_to lesson_takes_path(lesson), method: :delete do %>
                <button class="btn btn-primary btn-prof btn-take">履修中</button>
              <% end %>
            <% else %>
              <%= link_to lesson_takes_path(lesson), method: :post do %>
                <button class="btn btn-warning btn-prof btn-take">履修する</button>
              <% end %>
            <% end %>
          </td>

          <td>
            <%= link_to edit_lesson_path(lesson) do %>
              <button class="btn btn-default">編集</button>
            <% end %>
            <% if current_user.id == lesson.user_id %>
              <%= link_to lesson, method: :delete, data: { confirm: "本当によろしいですか？" } do %>
                <button class="btn btn-default">削除</button>
              <% end %>
            <% end %>
          </td>

        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @lessons %>
<% end %>
<br>

<%= link_to new_lesson_path do %>
  <button class="btn btn-default">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> 新しい授業を追加する
  </button>
<% end %>
</div>

app/views/lessons/new.html.erb
<div class="box">
<div class="page-header">
  <h1>新しい授業の追加 <span class="glyphicon glyphicon-book" aria-hidden="true"></span></h1>
</div>
<%= render 'form', lesson: @lesson %><br>

<%= link_to "授業一覧", lessons_path %>
</div>

app/views/lessons/show.html.erb
<div class="box">
<div class="page-header">
  <h3>授業詳細 <span class="glyphicon glyphicon-book" aria-hidden="true"></span></h3>
</div>
<p>
  <h1><%= @lesson.title %>【<%= @lesson.teacher %>】</h1>
</p>

<% if @lesson.taken_by? current_user %>
  <%= link_to lesson_takes_path(@lesson), method: :delete do %>
    <button class="btn btn-primary btn-prof btn-take">履修中</button>
  <% end %>
<% else %>
  <%= link_to lesson_takes_path(@lesson), method: :post do %>
    <button class="btn btn-warning btn-prof btn-take">履修する</button>
  <% end %>
<% end %>

<%= link_to takers_lesson_path(@lesson) do %>
  <button class="btn btn-success">
    履修者一覧 <span class="badge"><%= @lesson.takes.count %></span>
  </button>
<% end %>

<%= link_to edit_lesson_path(@lesson) do %>
  <button class="btn btn-default btn-xs">授業を編集</button>
<% end %>

<% if current_user.id == @lesson.user_id %>
  <%= link_to @lesson, method: :delete, data: { confirm: "本当によろしいですか？" } do %>
    <button class="btn btn-default btn-xs">授業を削除</button>
  <% end %>
<% end %>
<br>  

<div class="page-header">
  <h3>投稿されたレビュー <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></h3>
</div>
<% if @lesson.reviews.empty? %>
  <span>レビューがありません</span>
<% else %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>ユーザー</th>
        <th>本文</th>
        <th>投稿日時</th>
      </tr>
    </thead>

    <tbody>
  	  <% @reviews.each do |review| %>
  	    <tr>
  	      <td>
  	      	<% if review.user.image.present? %>
  	  	  	  <%= link_to user_path(review.user) do %>
  	  	  	    <%= image_tag review.user.image.url %>
  	  	  	  <% end %>
  	  	    <% else %>
  	  	  	  <%= link_to user_path(review.user) do %>
  	  	  	    <%= image_tag "http://res.cloudinary.com/dj4jxxpze/image/upload/v1507382061/no_image_qzetmh.png" %>
  	  	  	  <% end %>
  	  	    <% end %>
            <br>
            <%= link_to user_path(review.user) do %>
              <h4>
                <strong>
                  <%= review.user.name %><br>
                  @<%= review.user.username %>
                </strong>
              </h4>
            <% end %>
  	      </td>
  	      <td class="review-body"><%= review.body %></td>
          <td><%= review.created_at.strftime('%Y/%m/%d %H:%M') %></td>

          <td>
          <% if current_user.id == review.user_id %>
            <%= link_to lesson_reviews_path(review.lesson), method: :delete, data: { confirm: "本当によろしいですか？"} do %>
              <button class="btn btn-default">削除</button>
            <% end %>
          <% end %>
          </td>
  	    </tr>
  	  <% end %>
    </tbody>
  </table>
<% end %>
<br>

<div class="page-header">
  <h3>新規レビュー投稿 <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></h3>
</div>
<p>※250文字以下</p>
<%= form_for([@lesson,Review.new]) do |f| %>
  <div>
  	<%= f.text_area :body, :size => '80x7' %>
  </div>
  <div class="actions" >
  	<%= f.submit "投稿" %>
  </div>
<% end %><br>

<%= link_to new_lesson_path do %>
  <button class="btn btn-default btn-xs">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> 新しい授業を追加する
  </button>
<% end %>

<br><br>

<%= link_to "授業一覧", lessons_path %>

</div>

app/views/lessons/takers.html.erb
<div class="box">
<div class="page-header">
  <h1>
    <%= @lesson.title %>の履修者一覧 <i class="fa fa-users" aria-hidden="true"></i>【<%= @lesson.takes.count %>】
  </h1>
</div>

<div class="wrap clearfix">

<% if @takers.empty? %>
  <div>履修者がいません</div>
<% else %>
  <% @takers.each do |taker| %>
    <div class="users">


      <div class="user-image">
        <% if taker.user.image.present? %>
          <%= link_to user_path(taker.user) do %>
            <%= image_tag taker.user.image.url %>
          <% end %>
        <% else %>
          <%= link_to user_path(taker.user) do %>
            <%= image_tag "http://res.cloudinary.com/dj4jxxpze/image/upload/v1507382061/no_image_qzetmh.png" %>
          <% end %>
        <% end %>
      </div>

        <br>
        <%= link_to user_path(taker.user) do %>
          <h4><strong><%= taker.user.name %>@<%= taker.user.username %></strong></h4>
        <% end %>

        <div>
        <% if current_user != taker.user %>
          <% if taker.user.followed_by?(current_user) %>
            <%= link_to user_relationships_path(taker.user), method: :delete do %>
              <button class="btn btn-primary btn-index">フォロー中</button>
            <% end %>
          <% else %>
            <%= link_to user_relationships_path(taker.user), method: :post do %>
              <button class="btn btn-warning btn-index">フォローする</button>
            <% end %>
          <% end %>
        <% else %>
          <%= link_to edit_user_registration_path(current_user) do %>
            <button class="btn btn-success">
              プロフィール編集 <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
            </button>
          <% end %>
        <% end %>
        </div>

    </div>
  <% end %>
<% end %>

</div>

<%= link_to "授業詳細へ", lesson_path(@lesson) %>

</div>