config/routes.rb
Rails.application.routes.draw do
  get "/top" => "items#top"

  get "/about" => "items#about"

  get 'favorites/create'

  get 'favorites/destroy'

  get 'takes/create'

  get 'takes/destroy'

  get 'users/index'

  get 'users/show'


  devise_for :users, :controllers => {
   :registrations => 'users/registrations' 
  }

  resources :users do
  	get :takes, on: :member
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    get :favorites, on: :member
  end
  resources :lessons do
  	resource :takes, only: [:create, :destroy]
    get :takers, on: :member
    resource :reviews, only: [:create, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
  end
  root 'lessons#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :user, presence: true
  validates :user_id, uniqueness: { scope: :review_id }
  validates :review, presence: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  has_many :takes, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :title, presence: true
  validates :teacher, presence: true
  validates :user_id, presence: true

  def taken_by? user
  	takes.where(user_id: user.id).exists?
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: User
  belongs_to :followed, class_name: User

  validates :followed_id, presence: true
  validates :following_id, presence: true
  validates :following_id, uniqueness: { scope: :followed_id }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :lesson
  has_many :favorites, dependent: :destroy

  validates :user_id, presence: true
  validates :lesson_id, presence: true
  validates :body, presence: true, length: { maximum: 250 }

  def favorited_by? user
  	favorites.where(user_id: user.id).exists?
  end
end

app/models/take.rb
class Take < ApplicationRecord
  belongs_to :user
  belongs_to :lesson

  validates :user, presence: true
  validates :user_id, uniqueness: { scope: :lesson_id }
  validates :lesson, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lessons, dependent: :destroy
  has_many :takes, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship', foreign_key: :following_id
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :followed_id
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :following

  mount_uploader :image, ImageUploader

  validates :name,
    presence: true,
    length: { maximum: 8 }
  validates :username,
  	presence: true,
  	uniqueness: true,
  	length: { maximum: 15 },
  	format: { with: /\A[a-z0-9]+\z/i }
  validates :bio, length: { maximum: 160 } 

  def followed_by? user
    passive_relationships.find_by(following_id: user.id).present?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy, :takers]
  before_action :authenticate_user!
  # before_action :correct_user, only: [:edit, :update]
  before_action :correct_user, only: [:destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.page(params[:page]).per(10).order(created_at: :desc)
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @reviews = @lesson.reviews.order(created_at: :desc)
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)
    @lesson.user_id = current_user.id
    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: '授業を追加しました' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: '授業を編集しました' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: '授業を削除しました' }
      format.json { head :no_content }
    end
  end

  def takers
    @lesson = Lesson.find(params[:id])
    @takers = @lesson.takes.order(created_at: :desc)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:title, :teacher, :user_id)
    end
    def correct_user
      lesson = Lesson.find(params[:id])
      if current_user.id != lesson.user.id
        redirect_to root_path
      end
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def edit
  end

  def create
  	@lesson = Lesson.find(params[:lesson_id])
  	@review = current_user.reviews.build(body: params[:review][:body], lesson_id: @lesson.id)
  	if @review.save
  	  redirect_to lesson_url(@lesson), notice: "レビューを投稿しました"
  	else
  	  redirect_to lesson_url(@lesson), alert: "レビューを投稿できませんでした"
  	end
  end

  def destroy
  	review = Review.find_by!(lesson_id: params[:lesson_id], user_id: current_user.id)
  	review.destroy
  	redirect_to lesson_url(params[:lesson_id]), notice: "レビューを削除しました"
  end
end

app/controllers/takes_controller.rb
class TakesController < ApplicationController
  before_action :authenticate_user!
  def create
  	@lesson = Lesson.find(params[:lesson_id])
  	@take = current_user.takes.build(lesson: @lesson)
  	if @take.save
  	  redirect_to lessons_url, notice: "履修登録しました"
  	else
  	  redirect_to lessons_url, alert: "履修登録に失敗しました"
  	end
  end

  def destroy
  	@take = current_user.takes.find_by!(lesson_id: params[:lesson_id])
  	@take.destroy
  	redirect_to lessons_url, notice: "履修を取り消しました"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).per(20).order(created_at: :desc)
  end

  def show
  	@user = User.find(params[:id])
    @user_reviews = @user.reviews.order(created_at: :desc)
    @takes = @user.takes.order(created_at: :desc)
  end

  def takes
  	@user = User.find(params[:id])
    @user_lessons = @user.lessons.order(created_at: :desc)
  end

  def follows
  	@user = User.find(params[:id])
  	@follows = @user.followings.page(params[:page]).per(20).order(created_at: :desc)
  end

  def followers
  	@user = User.find(params[:id])
  	@followers = @user.followers.page(params[:page]).per(20).order(created_at: :desc)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/takes_helper.rb
module TakesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Review</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample7">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to top_path, class: "navbar-brand" do %>
            <strong>
              Review<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </strong>
          <% end %>
        </div>

        <!--例 <li>
          <%= link_to users_show_path(current_user) do %>
              <span class="glyphicon glyphicon-home" aria-hidden="true"> My Page</span>
          <% end %>
        </li> -->

        <div class="collapse navbar-collapse" id="navbarEexample7">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to about_path do %>
                <i class="fa fa-info-circle" aria-hidden="true"></i> 概要
              <% end %>
            </li>
            <% if user_signed_in? %>
              <li>
                <%= link_to lessons_path do %>
                  <span class="glyphicon glyphicon-book" aria-hidden="true"> 授業一覧</span>
                <% end %>
              </li>
              <li>
                <%= link_to users_path do %>
                  <i class="fa fa-users" aria-hidden="true"> 学生一覧</i>
                <% end %>
              </li>
              <li>
                <%= link_to user_path(current_user) do %>
                  <i class="fa fa-user" aria-hidden="true"> マイプロフィール</i>
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to new_user_registration_path do %>
                  <span class="glyphicon glyphicon-check" aria-hidden="true"> 新規登録</span>
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path do %>
                  <span class="glyphicon glyphicon-log-in" aria-hidden="true"> ログイン</span>
                <% end %>
              </li>
            <% end %>    
          </ul>
          <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <span class="glyphicon glyphicon-log-out" aria-hidden="true"> ログアウト</span>
                <% end %>
              </li>
            </ul>
            <p class="nav navbar-nav navbar-text navbar-right">
              <i class="fa fa-user" aria-hidden="true"></i> <%= current_user.name %>@<%= current_user.username %>としてログイン中
            </p>
          <% end %>
        </div>
      </div>
    </nav>

    <%= yield %>
    <br>
    <br>
    <div class="copy-right text-center">(C) 2017 Taira Kanakubo</div>

  </body>
</html>